### ISSUE TITLE
Google Drive uploading doesn't work

### ISSUE THREAD

**Issue by dixidroid** [uploadcare/uploadcare-android#12]
I can't upload any file using Google Drive

**Comment by dmitry-mukhin** [comment]
closing as non informative.

**Comment by dixidroid** [comment]
![1549777227821](https://user-images.githubusercontent.com/5153976/52530060-7f552280-2d20-11e9-93ef-b64ec4dfc711.JPEG)

**Comment by dmitry-mukhin** [comment]
this is better, thanks :)

**Comment by raphaelnew** [comment]
81a449841cb8af1f3fd5e1ec9afc55bf7f83e4a6 Closes this issue.

**Comment by dixidroid** [comment]
![1550501297104](https://user-images.githubusercontent.com/5153976/52958661-60a4fa80-33b6-11e9-911c-ebf7cdbc991c.JPEG)
doesn't work =(

**Comment by dmitry-mukhin** [comment]
"upload failed" can be raised for a number of reasons. If you get access to your Google Drive and are able to select a file, it means that this particular feature works.
We need more information to be able to figure out why upload itself fails.

**Comment by raphaelnew** [comment]
@dixidroid Please provide more info: UploadCare Android SDK version used, any other specific details like file meta-data or format. Or steps to reproduce the issue.
