### ISSUE TITLE
Don't store private key on client side

### ISSUE THREAD

**Issue by rsedykh** [uploadcare/uploadcare-android#22]
> I’m android developer and using Uploadcare. How can I use UploadcareClient without privatekey? (In Android) I just need to upload files not more. In most APIs UploadcareClient does not need privatekey. But in Android it is necessary and this is not safe. Nobody (professional developer) store private key in client side. this is so important subject and I wondered when I understood it as CTO. Anyway we can’t accept its risks because we set private key inside of our app and it can recovery easily by a “app cracker” so please check/report this problem to solve it in shortest time kindly.

**Comment by jlamson** [comment]
We're currently exploring if/how we'd like to use this sdk in an Android client, and this concerns me. I'd love to avoid the private key being used. 

@rsedykh any thoughts/progress on this?

**Comment by rsedykh** [comment]
Hey @jlamson. @dmitry-mukhin already answered you at https://github.com/uploadcare/uploadcare-java/issues/20, but I want to mention it here also, that we'll make `secret_key` optional for uploading files (if you don't need [signed uploads](https://uploadcare.com/docs/api_reference/upload/signed_uploads/), obviously).
