### ISSUE TITLE
Library does not work with AndroidX

### ISSUE THREAD

**Issue by MatthewCawley** [uploadcare/uploadcare-android#38]
### Describe the bug

Implementing UploadCare into a project using AndroidX throws the following error when calling:

`UploadcareWidget.getInstance(context).selectFile(this, true)`

`java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/databinding/DataBinderMapperImpl;`

Steps:
Implement Widget using instructions for Kotlin at https://github.com/uploadcare/uploadcare-android/blob/master/widget/README.md

### Expected behavior

Widget should load as designed.

### Environment

 - Library version: 2.2.0
 - Language/framework version: Kotlin
 - OS version: Android Q - API 29

**Comment by MatthewCawley** [comment]
This can be resolved by enabling data binding for kotlin projects:

Add the following to the project Gradle file

`classpath "org.jetbrains.kotlin:kotlin-android-extensions:$versions.kotlin_version"`


Add the following to the Module Gradle file

`apply plugin: 'kotlin-kapt'`

and

```
android {  
    dataBinding {
        enabled = true
    }
}
```

**Comment by raphaelnew** [comment]
Answered above.
