### ISSUE TITLE
Control of the image before upload

### ISSUE THREAD

**Issue by MatthewCawley** [uploadcare/uploadcare-android#39]
### Brief description of the feature and motivation behind it

For an implementation that I am working on, the client needs to be able to select an image, crop it to a set ratio and then upload the image. At present this is possible on the Web Plugin but not the Android plugin

The feature suggestion would be to add a pre-upload call back that returns the local file (if selected locally) or if the image is a social media image, the image is downloaded first and then passed to the user. 

Modifications can be then made to the image before passing to an upload method.

Ideally features such as cropping could be integrated as part of the Widget to avoid additional 3rd party integrations.

The lack of this feature has made me drop the usage of upload care in the android app as it cannot perform on par with the web implementation.

There are a lot of cases where the user may not want to use the image exactly as it is on their device or social media and giving the user the ability to make changes will be a massive benefit.

As an alternative, I've considered other platforms such as filestack.io or native implementations. 

**Current usage**
```
UploadcareWidget.getInstance(context).selectFileFrom(
                fragment,
                SocialNetwork.SOCIAL_NETWORK_FACEBOOK,
                FileType.image,
                storeUponUpload)
```

**Proposed new method with optional callback**
```
UploadcareWidget.getInstance(context).selectMutableFileFrom(
                fragment,
                SocialNetwork.SOCIAL_NETWORK_FACEBOOK,
                FileType.image) { image ->
                     //image object is returned here
                }
```

**Comment by dmitry-mukhin** [comment]
@MatthewCawley 
There is a core misconception here, that you can do something like this using Web Uploader.
You can't. The original file is being uploaded and then you can manipulate an image using our CDN  URL API (the dialog does this for you). In the end you get a URL with [transformations](https://uploadcare.com/docs/image_transformations/) added in the URL itself.

The same behaviour can (and should) be implemented in Android Lib. We're just not there yet.

**Comment by raphaelnew** [comment]
@MatthewCawley CDN urls (Image Transformations) are supported by Android client look for example and [documentation here](https://github.com/uploadcare/uploadcare-android/tree/master/library#building-cdn-urls)
