### ISSUE TITLE
signature: Secure uploads support

### ISSUE THREAD

**Issue by chinalwb** [uploadcare/uploadcare-android#40]
Hey guys! 

The demo app works great! However I don't see the support for `secure uploads` in the `library`, i.e.: I want to use [`secure uploads`](https://uploadcare.com/docs/security/secure_uploads/), but cannot set my signature into the `FileUploader` or `MultipleFilesUploader`.

Could you please check and make it available? Or if I am wrong, could you please guide me how to set my signature to the uploader?

Thanks.

**Comment by raphaelnew** [comment]
@chinalwb  We are currently working on it, "Signed uploads" will be available shortly in next version of the library.
