### ISSUE TITLE
Incorrect Response in FileUploader - onSuccess Method

### ISSUE THREAD

**Issue by zaeem-khatib** [uploadcare/uploadcare-android#54]
### Describe the bug

We're facing a strange issue, we're using the uploadcare Android library 3.1.0, we're using the uploadAsync method of the FileUploader object to upload images, the image upload succeeds and we can see the uploaded images on the Uploadcare web portal, in the Android code the onSuccess block of the uploadAsync method is called but the originalFileUrl and url properties of the UploadcareFile object are null. Also, the uploaded and stored date properties are null but when we open the image in the Uploadcare console all of these properties have their correct values so not sure what's going wrong in the Android SDK. The same issue occurs if we use the sync upload method.

### Expected behavior

The UploadcareFile object must have the correct originalFileUrl value.

### Code / screenshots

Upload code:

```
fun File.upload(callback: (FileUploadResult) -> Unit) {
    val bytes = readBytes()
    val client = UploadcareClient("###")
    val uploader = FileUploader(client, bytes, name).store(true)
    val defaultErrorMessage = "Error uploading file. Please try again later."

    uploader.uploadAsync(object : UploadFileCallback {
        override fun onFailure(e: UploadcareApiException) {
            callback(FileUploadResult(false, "", e.localizedMessage ?: defaultErrorMessage, ""))
        }

        override fun onProgressUpdate(
            bytesWritten: Long,
            contentLength: Long,
            progress: Double) {
        }

        override fun onSuccess(result: UploadcareFile) {
            callback(FileUploadResult(true, result.originalFileUrl.toString(), "", result.uuid) )
        }
    })
}
```

Response object:

`UploadcareFile
File id: f5fa549a-2d75-4df4-a2ee-8c6fd602e136
Url: null
Size: 60967
Mime type: image/png
is Ready: true
is Image: true
Original Filename: Asset Front@2x.png
Original File Url: null
Date uploaded: null
is Stored: false
Date stored: null
is Removed: false
Date removed: null
Source: null
Image Info: ImageInfo(format=PNG, height=226, width=310, orientation=null, sequence=false, colorMode=RGBA, geoLocation=null, datetimeOriginal=null, dpi=null)
Video Info: null
Variations: null
Rekognition Info: null`

### Environment

 - Library version: 3.1.0
 - Language/framework version: Kotlin 1.8
 - OS version: Android API Level 30

**Comment by rsedykh** [comment]
Hi @zaeem-khatib. We can't fix it asap, but we're on our way to update the lib and fix this issue too. I'll keep you posted, but I think it will take a month before it will be fixed. :-(

**Comment by zaeem-khatib** [comment]
Hello @rsedykh. I managed to 'fix' it by adding a secret to the initialisation method, either the documentation should be updated to reflect this or at least the onSuccess method shouldn't be called.

**Comment by rsedykh** [comment]
Yeah, that's an issue that early design of those libs asked for both public and secret keys even when there is no need for a secret key. :-(
