### ISSUE TITLE
API version migration from v0.6 to v0.7

### ISSUE THREAD

**Issue by CheK539** [uploadcare/uploadcare-android#78]
The following files will be changed as part of the migration:

- UploadcareFile:
Remove the following fields: `image_info`, `video_info`, `rekognition_info`, as they have been removed from the API scheme.
Add the following fields: `content_info`, `metadata`, `appdata`, as they have been added to the API scheme.

- UrlParameters:
Rename the `AddFieldsParameter` class to `IncludeParameter`.

- FilesQueryBuilder:
Rename the `addFields()` method to `include()`.

- UploadcareClient:
Rename the `getFileWithRekognitionInfo()` method to `getFileWithAppData()`.
Change the endpoint that the `deleteFile()` method is using to `apiFileStorage` because the old one was replaced with this one.
Remove the `storeGroup()` method, as its endpoint has been removed.
Change the `createWebhook()` and `updateWebhook()` methods' the type of parameter `event` to enum.

- FilesQueryBuilder:
Remove the sorting method by file size, as its parameter has been removed from the API query parameters.

- FilesFragment:
Remove sorting options by file size.

- UploadcareWebhook:
Change the type of parameter `event` to enum.
Add the following enum constants for event types: `file.uploaded`, `file.infected`, `file.stored`, `file.deleted`, `file.info_updated`.

**Comment by rsedykh** [comment]
👍

Can you also add new webhook event types (and clarify it in this issue/changelog)?
